"""Add product_cat column to Product

Revision ID: 220914f1b32e
Revises: 025a7eb85ece
Create Date: 2024-07-04 23:17:33.848510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220914f1b32e'
down_revision = '025a7eb85ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_cat', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('product_cat')

    # ### end Alembic commands ###
